const seed = [];

const uiPrefs=JSON.parse(localStorage.getItem('projectUiPrefs')||'{}');
const sortLabels={id:'编号',category:'分类',project:'名称',amount:'金额',cost:'成本',profit:'利润',date:'日期',owner:'负责人',client:'客户',paymentStatus:'收款状态'};
const state={records:JSON.parse(localStorage.getItem('projectRecords')||'null')||seed,search:'',status:'all',payment:'all',sortAsc:typeof uiPrefs.sortAsc==='boolean'?uiPrefs.sortAsc:false,sortField:Object.hasOwn(sortLabels,uiPrefs.sortField)?uiPrefs.sortField:'date',collapsedGroups:new Set(),history:[],editingKey:null,groupBy:uiPrefs.groupBy==='category'?'category':'project',hideDone:!!uiPrefs.hideDone,view:'table',customerSearch:'',customerFilter:'all',rowHeight:Number(uiPrefs.rowHeight)||38,columnWidth:['compact','standard','wide','extra'].includes(uiPrefs.columnWidth)?uiPrefs.columnWidth:'standard'};
let columnOrder=Array.from({length:14},(_,i)=>i);localStorage.removeItem('columnOrder');
const presetDefaults={category:['广告户'],project:['报白户'],owner:['TK-EDC'],status:['已付款','已退款','已提交','审核中','交付完成'],paymentStatus:['未收款','部分收款','已收款','已退款']};
const presets={...presetDefaults,...JSON.parse(localStorage.getItem('projectPresets')||'{}')};
state.records.forEach(r=>{if(r.owner==='杜阳')r.owner='TK-EDC';if(r.cost==null)r.cost='';r.paymentStatus??='未收款';r.statuses=Array.isArray(r.statuses)?r.statuses:[]});Object.keys(presets).filter(k=>!Object.hasOwn(presetDefaults,k)).forEach(k=>delete presets[k]);presets.owner=[...new Set((presets.owner||[]).map(v=>v==='杜阳'?'TK-EDC':v))];Object.keys(presetDefaults).forEach(k=>presets[k]=[...new Set([...(presets[k]||[]),...presetDefaults[k]])]);localStorage.setItem('projectRecords',JSON.stringify(state.records));localStorage.setItem('projectPresets',JSON.stringify(presets));
const $=s=>document.querySelector(s); const body=$('#tableBody');
const statusClass={'已付款':'paid','已退款':'refund','已提交':'submitted','审核中':'review','交付完成':'done'};
const projectThemes=[
  {accent:'#4f6ef7',soft:'#f7f8ff',strong:'#edf1ff',text:'#3549b3'},
  {accent:'#8b5cf6',soft:'#faf8ff',strong:'#f2edff',text:'#6941c6'},
  {accent:'#0891b2',soft:'#f3fbfd',strong:'#e6f8fc',text:'#08748d'},
  {accent:'#db2777',soft:'#fff7fb',strong:'#fceaf3',text:'#aa1d5b'},
  {accent:'#c26a16',soft:'#fffaf5',strong:'#fff0df',text:'#98500d'},
  {accent:'#0f8a6a',soft:'#f4fbf8',strong:'#e5f7f0',text:'#0c6b53'},
  {accent:'#2563eb',soft:'#f5f8ff',strong:'#e9f0ff',text:'#1d4fb9'},
  {accent:'#64748b',soft:'#f8fafc',strong:'#eef2f6',text:'#475569'},
  {accent:'#7c3aed',soft:'#faf7ff',strong:'#f1eaff',text:'#5b21b6'},
  {accent:'#0d9488',soft:'#f3fbfa',strong:'#e3f7f4',text:'#0f6f68'},
  {accent:'#ea580c',soft:'#fff8f4',strong:'#ffebdf',text:'#b84008'},
  {accent:'#a16207',soft:'#fffbf2',strong:'#fff3d6',text:'#7c4a03'}
];
const defaultProjectName='未命名项目',categoryTheme={accent:'#64748b',soft:'#f8fafc',strong:'#eef2f6',text:'#475569'};
function projectTheme(name){let hash=2166136261;for(const char of String(name||defaultProjectName)){hash^=char.codePointAt(0);hash=Math.imul(hash,16777619)>>>0}return projectThemes[hash%projectThemes.length]}
function themeStyle(theme){return `--project-accent:${theme.accent};--project-soft:${theme.soft};--project-soft-strong:${theme.strong};--project-text:${theme.text}`}
const cloud={client:null,user:null,timer:null,saving:false};
function save(){localStorage.setItem('projectRecords',JSON.stringify(state.records));scheduleCloudSave();toast(cloud.user?'正在同步到云端…':'已保存到本地')}
function snapshot(){state.history.push(JSON.stringify(state.records));if(state.history.length>20)state.history.shift()}
function sortValue(r,field){if(field==='profit')return (Number(r.amount)||0)-(Number(r.cost)||0);if(['amount','cost'].includes(field))return Number(r[field])||0;return String(r[field]||'')}
function filtered(){let rows=state.records.filter(r=>{const hay=Object.values(r).flat().join(' ').toLowerCase();return hay.includes(state.search.toLowerCase())&&(state.status==='all'||r.statuses.includes(state.status))&&(state.payment==='all'||r.paymentStatus===state.payment)&&(!state.hideDone||!r.statuses.includes('交付完成'))});return rows.sort((a,b)=>{const av=sortValue(a,state.sortField),bv=sortValue(b,state.sortField),result=typeof av==='number'?av-bv:String(av).localeCompare(String(bv),'zh-CN',{numeric:true});return (result||String(a.id).localeCompare(String(b.id),'zh-CN',{numeric:true}))*(state.sortAsc?1:-1)})}
function rowHtml(r,i,isLast=false){
  const profit=(Number(r.amount)||0)-(Number(r.cost)||0),projectName=r.project||defaultProjectName,theme=projectTheme(projectName),statuses=Array.isArray(r.statuses)?r.statuses:[];
  return `<tr class="data-row project-row ${isLast?'group-last':''}" style="${themeStyle(theme)}" data-key="${esc(r.key)}" tabindex="0" aria-label="编辑项目 ${esc(r.id)} ${esc(projectName)}"><td class="row-index"><span>${i+1}</span></td><td class="id-cell">${esc(r.id)}</td><td><span class="tag category">${esc(r.category)}</span></td><td class="project-cell" title="${esc(projectName)}"><span class="project-swatch" aria-hidden="true"></span><strong>${esc(projectName)}</strong></td><td class="amount">${r.amount?`¥${Number(r.amount).toLocaleString()}`:''}</td><td class="cost">${r.cost?`¥${Number(r.cost).toLocaleString()}`:''}</td><td class="profit ${profit<0?'negative':''}">¥${profit.toLocaleString()}</td><td>${esc(r.date||'')}</td><td><span class="avatar">◉</span>${esc(r.owner)}</td><td title="${esc(r.client)}">${esc(r.client)}</td><td><span class="payment-badge pay-${esc(r.paymentStatus||'未收款')}">${esc(r.paymentStatus||'未收款')}</span></td><td>${statuses.map(s=>`<span class="tag ${statusClass[s]||''}" data-status="${esc(s)}" title="点击编辑状态">${esc(s)}</span>`).join('')}</td><td title="${esc(r.note||'')}">${esc(r.note||'')}</td><td title="${esc(r.files||'')}">${esc(r.files||'')}</td></tr>`
}
function groupSummary(items){
  const amount=items.reduce((n,r)=>n+(Number(r.amount)||0),0),cost=items.reduce((n,r)=>n+(Number(r.cost)||0),0),profit=amount-cost,pending=items.filter(r=>!(r.statuses||[]).includes('交付完成')).length,unpaid=items.filter(r=>['未收款','部分收款'].includes(r.paymentStatus)).length;
  return `<span class="group-summary"><span class="group-metric"><b>${items.length}</b> 条</span><span class="group-metric">金额 <b>¥${amount.toLocaleString()}</b></span><span class="group-metric group-profit ${profit<0?'negative':''}">利润 <b>¥${profit.toLocaleString()}</b></span><span class="group-metric ${pending?'attention':'complete'}">${pending?`待交付 ${pending}`:'已全部交付'}</span><span class="group-metric ${unpaid?'attention':'complete'}">${unpaid?`待收款 ${unpaid}`:'已结清'}</span></span>`
}
function render(){
  const rows=filtered(),fallback=state.groupBy==='project'?defaultProjectName:'未分类',groups=Object.groupBy?Object.groupBy(rows,r=>r[state.groupBy]||fallback):rows.reduce((o,r)=>((o[r[state.groupBy]||fallback]??=[]).push(r),o),{});let index=0;
  body.innerHTML=Object.entries(groups).map(([name,items])=>{const collapsed=state.collapsedGroups.has(name),label=state.groupBy==='project'?'项目':'分类',theme=state.groupBy==='project'?projectTheme(name):categoryTheme,secondary=state.groupBy==='project'?[...new Set(items.map(r=>r.category).filter(Boolean))].slice(0,2).join('、'):`${new Set(items.map(r=>r.project||defaultProjectName)).size} 个项目`;return `<tr class="group-row ${collapsed?'collapsed':''}" style="${themeStyle(theme)}" data-group="${esc(name)}"><td colspan="14"><span class="chev">⌄</span><span class="group-type">${label}</span><strong class="group-title" title="${esc(name)}">${esc(name)}</strong>${secondary?`<span class="group-secondary">${esc(secondary)}</span>`:''}${groupSummary(items)}</td></tr>`+(collapsed?'':items.map((r,itemIndex)=>rowHtml(r,index++,itemIndex===items.length-1)).join(''))}).join('');
  applyColumnOrder();document.querySelectorAll('#tableBody td').forEach(td=>td.style.height=state.rowHeight+'px');$('#recordCount').textContent=`${rows.length} 条记录`;$('#emptyState').classList.toggle('show',!rows.length);bindRows();if(state.view==='table')renderQuickStats();else if(state.view==='board')renderBoard();else if(state.view==='finance')renderFinance();else renderCustomerDirectory();updateStickyOffsets()
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bindRows(){document.querySelectorAll('.group-row').forEach(x=>x.onclick=()=>{const name=x.dataset.group;state.collapsedGroups.has(name)?state.collapsedGroups.delete(name):state.collapsedGroups.add(name);render()});document.querySelectorAll('.data-row').forEach(x=>{const open=()=>openModal(state.records.find(v=>String(v.key)===x.dataset.key));x.onclick=open;x.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function currentStatus(r){return [...allStatuses].reverse().find(s=>r.statuses.includes(s))||r.statuses.at(-1)||'未设置'}
function aggregate(rows,keyFn,valueFn=()=>1){return Object.entries(rows.reduce((o,r)=>{const k=keyFn(r)||'未设置';o[k]=(o[k]||0)+valueFn(r);return o},{})).sort((a,b)=>b[1]-a[1])}
function bars(data,color='',money=false){const max=Math.max(1,...data.map(x=>x[1]));return data.length?data.map(([label,value])=>`<div class="bar-row"><span class="bar-label" title="${esc(label)}">${esc(label)}</span><div class="bar-track"><div class="bar-fill ${color}" style="width:${Math.max(2,value/max*100)}%"></div></div><span class="bar-value">${money?'¥'+Number(value).toLocaleString():value}</span></div>`).join(''):'<div class="chart-empty">暂无数据</div>'}
function projectBars(data){const max=Math.max(1,...data.map(x=>Math.abs(x[1])));return data.length?data.map(([label,value])=>{const theme=projectTheme(label);return `<div class="bar-row project-bar" style="${themeStyle(theme)}"><span class="bar-label project-bar-label" title="${esc(label)}"><i></i>${esc(label)}</span><div class="bar-track"><div class="bar-fill project-profit ${value<0?'negative':''}" style="width:${Math.max(2,Math.abs(value)/max*100)}%"></div></div><span class="bar-value ${value<0?'negative':''}">¥${Number(value).toLocaleString()}</span></div>`}).join(''):'<div class="chart-empty">暂无数据</div>'}
function donut(data){const colors=['#536ff4','#22c55e','#f59e0b','#f97316','#a855f7','#06b6d4'],rawTotal=data.reduce((n,x)=>n+x[1],0),scale=rawTotal||1;let cursor=0;const stops=data.map((x,i)=>{const start=cursor;cursor+=x[1]/scale*100;return `${colors[i%colors.length]} ${start}% ${cursor}%`}).join(',');return `<div class="donut-layout"><div class="donut" style="background:conic-gradient(${stops||'#eef1f5 0 100%'})"><div><strong>${rawTotal}</strong><span>项目</span></div></div><div class="donut-legend">${data.map((x,i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join('')}</div></div>`}
function renderBoard(){const rows=state.records,total=rows.reduce((n,r)=>n+(Number(r.amount)||0),0),cost=rows.reduce((n,r)=>n+(Number(r.cost)||0),0),profit=total-cost,done=rows.filter(r=>r.statuses.includes('交付完成')).length,unpaid=rows.filter(r=>['未收款','部分收款'].includes(r.paymentStatus)).length,clients=new Set(rows.map(r=>r.client).filter(Boolean)).size,statusData=aggregate(rows,currentStatus),categoryData=aggregate(rows,r=>r.category),paymentData=aggregate(rows,r=>r.paymentStatus),projectProfit=aggregate(rows,r=>r.project,r=>(Number(r.amount)||0)-(Number(r.cost)||0));$('#boardWrap').innerHTML=`<div class="chart-dashboard"><div class="dashboard-intro"><div><span>完整业务概览</span><h3>项目经营数据一览</h3><p>展示全部项目，不受进度表筛选条件影响</p></div><div class="completion-ring"><strong>${rows.length?Math.round(done/rows.length*100):0}%</strong><span>交付率</span></div></div><div class="metric-grid"><div class="metric-card blue"><span>项目总数</span><strong>${rows.length}</strong><small>${clients} 位客户</small></div><div class="metric-card"><span>项目总金额</span><strong>¥${total.toLocaleString()}</strong><small>累计业务收入</small></div><div class="metric-card profit"><span>预计利润</span><strong>¥${profit.toLocaleString()}</strong><small>收入减去项目成本</small></div><div class="metric-card warning"><span>待收款项目</span><strong>${unpaid}</strong><small>未收款或部分收款</small></div></div><div class="chart-grid"><section class="chart-panel"><div class="panel-title"><h3>阶段状态占比</h3><span>项目阶段</span></div>${donut(statusData)}</section><section class="chart-panel"><div class="panel-title"><h3>项目分类分布</h3><span>按项目数量</span></div>${bars(categoryData,'green')}</section><section class="chart-panel"><div class="panel-title"><h3>收款状态分布</h3><span>回款情况</span></div>${bars(paymentData,'')}</section><section class="chart-panel"><div class="panel-title"><h3>项目利润排行</h3><span>项目颜色与进度表一致</span></div>${projectBars(projectProfit.slice(0,8))}</section></div></div>`}
function renderQuickStats(){const rows=filtered(),amount=rows.reduce((n,r)=>n+(Number(r.amount)||0),0),cost=rows.reduce((n,r)=>n+(Number(r.cost)||0),0),pending=rows.filter(r=>!r.statuses.includes('交付完成')).length,unpaid=rows.filter(r=>['未收款','部分收款'].includes(r.paymentStatus)).length;$('#quickStats').innerHTML=`<div class="quick-stat"><i>￥</i><div><small>项目总金额 / 利润</small><strong>¥${amount.toLocaleString()} / ¥${(amount-cost).toLocaleString()}</strong></div></div><div class="quick-stat cost"><i>◎</i><div><small>项目总成本</small><strong>¥${cost.toLocaleString()}</strong></div></div><div class="quick-stat warning"><i>◷</i><div><small>待交付项目</small><strong>${pending}</strong></div></div><div class="quick-stat success"><i>￥</i><div><small>待收款项目</small><strong>${unpaid}</strong></div></div>`}
function isoWeek(dateText){const d=new Date(dateText+'T00:00:00');if(Number.isNaN(d.getTime()))return '日期未设置';d.setHours(0,0,0,0);d.setDate(d.getDate()+3-(d.getDay()+6)%7);const year=d.getFullYear(),week=1+Math.round(((d-new Date(year,0,4))/86400000-3+(new Date(year,0,4).getDay()+6)%7)/7);return `${year} 年第 ${String(week).padStart(2,'0')} 周`}
function financeGroups(rows,keyFn){return Object.entries(rows.reduce((o,r)=>{const key=keyFn(r),item=o[key]??={count:0,total:0,cost:0};item.count++;item.total+=Number(r.amount)||0;item.cost+=Number(r.cost)||0;return o},{})).sort((a,b)=>b[0].localeCompare(a[0]))}
function reportRows(groups){return groups.length?groups.map(([period,v])=>`<tr><td>${esc(period)}</td><td>${v.count}</td><td class="report-money">¥${v.total.toLocaleString()}</td><td class="report-money">¥${v.cost.toLocaleString()}</td><td class="report-money">¥${(v.total-v.cost).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="5">暂无可统计数据</td></tr>'}
function financeTrend(groups){const recent=groups.slice(0,6).reverse(),max=Math.max(1,...recent.map(x=>x[1].total));return `<div class="trend-chart">${recent.map(([period,v])=>`<div class="trend-item"><div class="trend-bars"><i class="income" style="height:${Math.max(4,v.total/max*100)}%" title="收入 ¥${v.total}"></i><i class="expense" style="height:${Math.max(3,v.cost/max*100)}%" title="成本 ¥${v.cost}"></i></div><span>${esc(period.slice(5)||period)}</span></div>`).join('')}</div><div class="trend-legend"><span><i class="income"></i>收入</span><span><i class="expense"></i>成本</span></div>`}
function renderFinance(){const rows=state.records.filter(r=>r.date),total=rows.reduce((n,r)=>n+(Number(r.amount)||0),0),cost=rows.reduce((n,r)=>n+(Number(r.cost)||0),0),profit=total-cost,margin=total?Math.round(profit/total*100):0,day=financeGroups(rows,r=>r.date),month=financeGroups(rows,r=>r.date.slice(0,7)),week=financeGroups(rows,r=>isoWeek(r.date));$('#financeWrap').innerHTML=`<div class="finance-dashboard"><div class="finance-hero"><div><span>财务中心</span><h3>收入、成本与利润分析</h3><p>所有数据根据项目金额、成本和开始时间自动汇总</p></div><div class="margin-card"><strong>${margin}%</strong><span>综合利润率</span></div></div><div class="metric-grid"><div class="metric-card blue"><span>累计项目金额</span><strong>¥${total.toLocaleString()}</strong><small>${rows.length} 个项目</small></div><div class="metric-card cost-card"><span>累计项目成本</span><strong>¥${cost.toLocaleString()}</strong><small>占收入 ${total?Math.round(cost/total*100):0}%</small></div><div class="metric-card profit"><span>累计项目利润</span><strong>¥${profit.toLocaleString()}</strong><small>利润率 ${margin}%</small></div><div class="metric-card"><span>平均项目利润</span><strong>¥${rows.length?Math.round(profit/rows.length).toLocaleString():0}</strong><small>单项目平均贡献</small></div></div><section class="finance-panel trend-panel"><div class="panel-title"><h3>月度收支趋势</h3><span>最近 6 个月</span></div>${financeTrend(month)}</section><div class="finance-grid"><section class="finance-panel"><div class="panel-title"><h3>每日财务报表</h3><span>${day.length} 个日期</span></div><div class="report-scroll"><table class="report-table"><thead><tr><th>日期</th><th>项目数</th><th>总金额</th><th>总成本</th><th>利润</th></tr></thead><tbody>${reportRows(day)}</tbody></table></div></section><section class="finance-panel"><div class="panel-title"><h3>每周财务报表</h3><span>${week.length} 个周次</span></div><div class="report-scroll"><table class="report-table"><thead><tr><th>周次</th><th>项目数</th><th>总金额</th><th>总成本</th><th>利润</th></tr></thead><tbody>${reportRows(week)}</tbody></table></div></section><section class="finance-panel finance-month"><div class="panel-title"><h3>每月财务报表</h3><span>${month.length} 个月份</span></div><div class="report-scroll"><table class="report-table"><thead><tr><th>月份</th><th>项目数</th><th>总金额</th><th>总成本</th><th>利润</th></tr></thead><tbody>${reportRows(month)}</tbody></table></div></section></div></div>`}
function customerProfiles(){const map=new Map();let missing=0;state.records.forEach(r=>{const contact=String(r.client||'').trim();if(!contact){missing++;return}const item=map.get(contact)||{contact,records:[],projects:new Set(),latestDate:''};item.records.push(r);item.projects.add(r.project||defaultProjectName);if((r.date||'')>=item.latestDate)item.latestDate=r.date||'';map.set(contact,item)});return {items:[...map.values()].sort((a,b)=>String(b.latestDate).localeCompare(String(a.latestDate))||a.contact.localeCompare(b.contact,'zh-CN',{numeric:true})),missing}}
function customerProjectRecords(profile){return profile.records.slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,3).map(r=>`<div class="customer-project-record" style="${themeStyle(projectTheme(r.project))}"><i></i><span title="${esc(r.project||defaultProjectName)}">${esc(r.project||defaultProjectName)}</span><small>${esc(r.id||'')}</small></div>`).join('')+(profile.records.length>3?`<span class="customer-more">+${profile.records.length-3}</span>`:'')}
function filteredCustomers(items){const q=state.customerSearch.trim().toLowerCase();return items.filter(item=>!q||[item.contact,...item.projects,...item.records.map(r=>r.id)].join(' ').toLowerCase().includes(q))}
function openCustomerProjects(contact){state.search=contact||'';state.status='all';state.payment='all';state.hideDone=false;$('#tableSearch').value=state.search;$('#statusFilter').value='all';$('#paymentFilter').value='all';$('#hideDone').checked=false;updateFilterText();saveUiPrefs();setView('table')}
function updateCustomerList(items=customerProfiles().items){const rows=filteredCustomers(items),tbody=$('#customerTableBody'),count=$('#customerResultCount');if(!tbody)return;if(count)count.textContent=`${rows.length} 位客户`;tbody.innerHTML=rows.length?rows.map(item=>{const theme=projectTheme(item.contact);return `<tr class="customer-row"><td><div class="customer-name"><span class="customer-avatar" style="${themeStyle(theme)}">${esc(item.contact.slice(0,1).toUpperCase())}</span><div><strong title="${esc(item.contact)}">${esc(item.contact)}</strong><small>来自项目中的客户信息</small></div></div></td><td><div class="customer-projects">${customerProjectRecords(item)}</div></td><td class="customer-number">${item.records.length} 条</td><td><button class="customer-open" type="button" data-client="${esc(item.contact)}">查看记录</button></td></tr>`}).join(''):'<tr><td colspan="4"><div class="customer-empty">暂无匹配的客户资料</div></td></tr>';document.querySelectorAll('.customer-open').forEach(btn=>btn.onclick=()=>openCustomerProjects(btn.dataset.client))}
function renderCustomerDirectory(){const data=customerProfiles(),items=data.items,repeat=items.filter(x=>x.records.length>1).length;$('#customerWrap').innerHTML=`<div class="customer-dashboard"><div class="customer-hero"><div><span>客户资料中心</span><h3>客户联系方式与项目记录</h3><p>自动从项目里的“客户信息”整理；填写姓名、微信或手机号即可留存</p></div><div class="customer-total"><strong>${items.length}</strong><span>位客户</span></div></div><div class="customer-metrics"><div class="customer-metric"><span>客户资料</span><strong>${items.length}</strong><small>${data.missing} 条项目未填写客户信息</small></div><div class="customer-metric blue"><span>关联项目记录</span><strong>${state.records.filter(r=>String(r.client||'').trim()).length}</strong><small>已按客户自动归档</small></div><div class="customer-metric"><span>复购客户</span><strong>${repeat}</strong><small>关联 2 条以上项目记录</small></div></div><div class="customer-toolbar"><label class="customer-search"><span>⌕</span><input id="customerSearch" value="${esc(state.customerSearch)}" placeholder="搜索联系方式、项目名称或编号" /></label><span id="customerResultCount"></span></div><div class="customer-table-card"><table class="customer-table"><thead><tr><th>客户联系方式</th><th>项目记录</th><th>记录数</th><th>操作</th></tr></thead><tbody id="customerTableBody"></tbody></table></div></div>`;$('#customerSearch').oninput=e=>{state.customerSearch=e.target.value;updateCustomerList(items)};updateCustomerList(items)}
const columnWidthStorageKey='projectCustomColumnWidths';
function savedColumnWidths(){try{return JSON.parse(localStorage.getItem(columnWidthStorageKey)||'{}')}catch{return {}}}
function restoreColumnWidths(){const saved=savedColumnWidths();document.querySelectorAll('colgroup col').forEach(col=>{const width=Number(saved[col.dataset.col]);if(width>=80)col.style.width=width+'px'});updateStickyOffsets()}
function rememberColumnWidth(col){const saved=savedColumnWidths();saved[col.dataset.col]=Math.round(col.getBoundingClientRect().width);localStorage.setItem(columnWidthStorageKey,JSON.stringify(saved))}
function updateStickyOffsets(){const wrap=$('.table-wrap'),cols=[...document.querySelectorAll('colgroup col')];if(!wrap||cols.length<4)return;let left=0;for(let i=0;i<4;i++){wrap.style.setProperty(`--sticky-${i+1}`,left+'px');left+=cols[i].getBoundingClientRect().width}}
function initColumnResize(){document.querySelectorAll('thead th').forEach((th,index)=>{if(index===0)return;const handle=document.createElement('span');handle.className='col-resizer';th.appendChild(handle);handle.onclick=e=>e.stopPropagation();handle.onmousedown=e=>{e.preventDefault();e.stopPropagation();const col=document.querySelector(`colgroup col[data-col="${th.dataset.col}"]`),start=e.clientX,startWidth=col.getBoundingClientRect().width;handle.classList.add('dragging');document.body.classList.add('resizing-column');const move=ev=>{col.style.width=Math.max(80,startWidth+ev.clientX-start)+'px';updateStickyOffsets()};const up=()=>{rememberColumnWidth(col);handle.classList.remove('dragging');document.body.classList.remove('resizing-column');document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up)};document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}})}
function initColumnMovement(){document.querySelectorAll('thead th').forEach((el,i)=>el.dataset.col=i);document.querySelectorAll('colgroup col').forEach((el,i)=>el.dataset.col=i)}
function applyColumnOrder(){const header=document.querySelector('thead tr'),cols=document.querySelector('colgroup');columnOrder.forEach(i=>{const th=header.querySelector(`[data-col="${i}"]`);if(th)header.appendChild(th);const col=cols.querySelector(`[data-col="${i}"]`);if(col)cols.appendChild(col)});document.querySelectorAll('.data-row').forEach(row=>{[...row.children].forEach((cell,i)=>cell.dataset.col=i);columnOrder.forEach(i=>{const cell=row.querySelector(`[data-col="${i}"]`);if(cell)row.appendChild(cell)})})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1600)}
function downloadFile(name,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportHtml(){const rows=state.records,total=rows.reduce((n,r)=>n+(Number(r.amount)||0),0),cost=rows.reduce((n,r)=>n+(Number(r.cost)||0),0),trs=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.id)}</td><td>${esc(r.category)}</td><td>${esc(r.project)}</td><td>¥${Number(r.amount||0).toLocaleString()}</td><td>¥${Number(r.cost||0).toLocaleString()}</td><td>¥${(Number(r.amount||0)-Number(r.cost||0)).toLocaleString()}</td><td>${esc(r.date)}</td><td>${esc(r.owner)}</td><td>${esc(r.client)}</td><td>${esc(r.paymentStatus||'')}</td><td>${r.statuses.map(esc).join('、')}</td><td>${esc(r.note||'')}</td><td>${esc(r.files||'')}</td></tr>`).join('');const html=`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>项目记录导出</title><style>body{font-family:Arial,"Microsoft YaHei";padding:28px;color:#303642}h1{margin-bottom:6px}.summary{display:flex;gap:12px;margin:20px 0}.card{padding:15px 20px;background:#f3f6fb;border-radius:8px}.card b{display:block;font-size:22px;margin-top:6px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border:1px solid #dfe3e8;text-align:left}th{background:#f3f5f8}@media print{body{padding:0}}</style></head><body><h1>项目记录报表</h1><div>导出时间：${new Date().toLocaleString()}</div><div class="summary"><div class="card">项目数<b>${rows.length}</b></div><div class="card">总金额<b>¥${total.toLocaleString()}</b></div><div class="card">总成本<b>¥${cost.toLocaleString()}</b></div><div class="card">总利润<b>¥${(total-cost).toLocaleString()}</b></div></div><table><thead><tr><th>#</th><th>ID</th><th>分类</th><th>项目名称</th><th>金额</th><th>成本</th><th>利润</th><th>开始</th><th>负责人</th><th>客户</th><th>收款</th><th>状态</th><th>备注</th><th>资料</th></tr></thead><tbody>${trs}</tbody></table></body></html>`;downloadFile(`项目记录-${new Date().toISOString().slice(0,10)}.html`,html,'text/html;charset=utf-8');toast('HTML 已导出')}
function sqlText(v){return v==null?'NULL':`'${String(v).replaceAll("'","''")}'`}
function exportDatabase(){const lines=['PRAGMA foreign_keys = ON;','BEGIN TRANSACTION;','CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, category TEXT, project_name TEXT, amount REAL DEFAULT 0, cost REAL DEFAULT 0, start_date TEXT, owner TEXT, client TEXT, payment_status TEXT, statuses TEXT, note TEXT, files TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);','CREATE TABLE IF NOT EXISTS presets (preset_type TEXT NOT NULL, preset_value TEXT NOT NULL, UNIQUE(preset_type, preset_value));','DELETE FROM projects;','DELETE FROM presets;'];state.records.forEach(r=>lines.push(`INSERT INTO projects (id,category,project_name,amount,cost,start_date,owner,client,payment_status,statuses,note,files) VALUES (${sqlText(r.id)},${sqlText(r.category)},${sqlText(r.project)},${Number(r.amount)||0},${Number(r.cost)||0},${sqlText(r.date)},${sqlText(r.owner)},${sqlText(r.client)},${sqlText(r.paymentStatus||'未收款')},${sqlText(JSON.stringify(r.statuses))},${sqlText(r.note||'')},${sqlText(r.files||'')});`));Object.entries(presets).forEach(([type,values])=>values.forEach(value=>lines.push(`INSERT OR IGNORE INTO presets (preset_type,preset_value) VALUES (${sqlText(type)},${sqlText(value)});`)));lines.push('COMMIT;');downloadFile(`项目数据库-${new Date().toISOString().slice(0,10)}.sql`,lines.join('\n'),'application/sql;charset=utf-8');toast('SQLite 数据库脚本已导出')}
let searchTimer;
$('#filterBtn').onclick=()=>$('#filterPanel').classList.toggle('show');
$('#tableSearch').oninput=e=>{state.search=e.target.value;updateFilterText();clearTimeout(searchTimer);searchTimer=setTimeout(render,140)};
$('#clearSearch').onclick=()=>{clearTimeout(searchTimer);state.search='';$('#tableSearch').value='';updateFilterText();render();$('#tableSearch').focus()};
$('#statusFilter').onchange=e=>{state.status=e.target.value;updateFilterText();render()};
$('#paymentFilter').onchange=e=>{state.payment=e.target.value;updateFilterText();render()};
$('#clearFilter').onclick=()=>{state.status='all';state.payment='all';$('#statusFilter').value='all';$('#paymentFilter').value='all';updateFilterText();render()};
function updateFilterText(){const n=[state.status,state.payment].filter(v=>v!=='all').length;$('#filterText').textContent=n?`${n} 个筛选`:'筛选';$('#filterBtn').classList.toggle('active-filter',n>0);$('#clearFilter').classList.toggle('show',n>0);$('#clearSearch').classList.toggle('show',!!state.search)}
function refreshSortUi(){document.querySelectorAll('[data-sort]').forEach(th=>{const active=th.dataset.sort===state.sortField;th.classList.toggle('active-sort',active);th.setAttribute('aria-sort',active?(state.sortAsc?'ascending':'descending'):'none');const icon=th.querySelector('.sort-indicator');if(icon)icon.textContent=active?(state.sortAsc?'↑':'↓'):'⇅'});$('#sortText').textContent=(sortLabels[state.sortField]||'日期')+(state.sortAsc?'升序':'降序')}
function sortBy(field){if(state.sortField===field)state.sortAsc=!state.sortAsc;else{state.sortField=field;state.sortAsc=true}saveUiPrefs();refreshSortUi();render()}
document.querySelectorAll('[data-sort]').forEach(th=>{th.tabIndex=0;th.onclick=()=>sortBy(th.dataset.sort);th.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();sortBy(th.dataset.sort)}}});
$('#sortBtn').onclick=()=>sortBy(state.sortField);
$('#groupBtn').onclick=()=>{state.groupBy=state.groupBy==='project'?'category':'project';$('#groupBtn').textContent=state.groupBy==='project'?'▦ 按项目分组':'▦ 按分类分组';state.collapsedGroups.clear();saveUiPrefs();render()};
function saveUiPrefs(){localStorage.setItem('projectUiPrefs',JSON.stringify({rowHeight:state.rowHeight,columnWidth:state.columnWidth,hideDone:state.hideDone,groupBy:state.groupBy,sortField:state.sortField,sortAsc:state.sortAsc}))}function applyColumnWidth(){const table=document.querySelector('.table-wrap table');table.dataset.width=state.columnWidth;table.querySelectorAll('col').forEach(col=>col.style.width='');updateStickyOffsets()}$('#rowHeight').onchange=e=>{state.rowHeight=Number(e.target.value);saveUiPrefs();render()};$('#columnWidth').onchange=e=>{state.columnWidth=e.target.value;localStorage.removeItem(columnWidthStorageKey);applyColumnWidth();saveUiPrefs()};$('#hideDone').onchange=e=>{state.hideDone=e.target.checked;saveUiPrefs();render()};function setView(view){state.view=view;const isTable=view==='table',meta={table:['项目进度表','集中管理每日项目、客户和阶段状态'],customers:['客户资料','按客户整理项目、金额、利润和待办状态'],board:['项目数据图表','完整项目的分类、阶段、回款与利润全貌'],finance:['财务报表','按日、周、月跟踪收入、成本与利润']}[view];$('#viewTitle').textContent=meta[0];$('#viewDescription').textContent=meta[1];$('.table-wrap').classList.toggle('hidden',!isTable);$('.toolbar').classList.toggle('view-hidden',!isTable);$('#filterPanel').classList.toggle('view-hidden',!isTable);$('#quickStats').classList.toggle('hidden',!isTable);document.querySelector('footer').classList.toggle('view-hidden',!isTable);$('#boardWrap').classList.toggle('show',view==='board');$('#financeWrap').classList.toggle('show',view==='finance');$('#customerWrap').classList.toggle('show',view==='customers');[['#navTable','table'],['#navCustomers','customers'],['#navBoard','board'],['#navFinance','finance']].forEach(([selector,name])=>$(selector).classList.toggle('active',view===name));render()}$('#navTable').onclick=()=>setView('table');$('#navCustomers').onclick=()=>setView('customers');$('#navBoard').onclick=()=>setView('board');$('#navFinance').onclick=()=>setView('finance');
$('#exportHtmlBtn').onclick=exportHtml;$('#exportDbBtn').onclick=exportDatabase;
const modal=$('#recordModal'),form=$('#recordForm'),defaultStatuses=presetDefaults.status;let allStatuses=[];
function syncStatuses(){allStatuses=[...new Set([...defaultStatuses,...presets.status,...JSON.parse(localStorage.getItem('customStatuses')||'[]'),...state.records.flatMap(r=>r.statuses||[])])]}
syncStatuses();
function updateStatusFilter(){const current=$('#statusFilter').value;$('#statusFilter').innerHTML='<option value="all">全部</option>'+allStatuses.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('#statusFilter').value=allStatuses.includes(current)?current:'all'}
function unique(field){return [...new Set([...(presets[field]||[]),...state.records.map(r=>r[field])].filter(v=>v!==''&&v!=null))]}
function selectOptions(selector,field,label){const values=unique(field);$(selector).innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')+`<option value="__new__">＋ 新增${label}…</option>`}
function fillOptions(){const fields={id:'idOptions',amount:'amountOptions',cost:'costOptions',client:'clientOptions',note:'noteOptions',files:'fileOptions'};Object.entries(fields).forEach(([field,id])=>{$('#'+id).innerHTML=unique(field).map(v=>`<option value="${esc(v)}"></option>`).join('')});selectOptions('#categorySelect','category','项目分类');selectOptions('#projectSelect','project','项目名称');selectOptions('#ownerSelect','owner','负责人');selectOptions('#paymentSelect','paymentStatus','收款状态')}
function statusOptions(selected=[]){$('#statusPicker').innerHTML=allStatuses.map(s=>`<label class="status-option ${statusClass[s]||''}"><input type="checkbox" name="statuses" value="${esc(s)}" ${selected.includes(s)?'checked':''}>${esc(s)}</label>`).join('')}
const presetModal=$('#presetModal'),presetMeta={category:'项目分类',project:'项目名称',owner:'负责人',status:'阶段状态',paymentStatus:'收款状态'};
function savePresets(){localStorage.setItem('projectPresets',JSON.stringify(presets));syncStatuses();updateStatusFilter();scheduleCloudSave();render();toast(cloud.user?'预设已同步':'预设已保存')}
function renderPresets(){
  $('#presetSections').innerHTML=Object.entries(presetMeta).map(([key,label])=>`<section class="preset-section" data-preset="${key}"><h3>${label}</h3><div class="preset-add"><input placeholder="输入新的${label}"><button type="button" data-add-preset="${key}">新增</button></div><div class="preset-chips">${presets[key].map((v,i)=>`<span class="preset-chip">${esc(v)}<button class="rename-preset" type="button" data-rename-preset="${key}" data-index="${i}" title="修改并同步历史项目">✎</button><button type="button" data-remove-preset="${key}" data-index="${i}" title="删除预设">×</button></span>`).join('')}</div></section>`).join('');
  document.querySelectorAll('[data-add-preset]').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.addPreset,input=btn.previousElementSibling,value=input.value.trim();if(!value)return toast('请输入预设内容');if(!presets[key].includes(value))presets[key].push(value);savePresets();renderPresets()});
  document.querySelectorAll('[data-rename-preset]').forEach(btn=>btn.onclick=async()=>{const key=btn.dataset.renamePreset,index=Number(btn.dataset.index),oldValue=presets[key][index],newValue=prompt(`修改${presetMeta[key]}`,oldValue)?.trim();if(!newValue||newValue===oldValue)return;if(presets[key].includes(newValue))return toast('该预设已存在');snapshot();presets[key][index]=newValue;if(key==='status')state.records.forEach(r=>r.statuses=r.statuses.map(s=>s===oldValue?newValue:s));else state.records.forEach(r=>{if(r[key]===oldValue)r[key]=newValue});localStorage.setItem('projectRecords',JSON.stringify(state.records));await deleteCloudPreset(key,oldValue);savePresets();renderPresets();toast('预设及历史项目已同步')});
  document.querySelectorAll('[data-remove-preset]').forEach(btn=>btn.onclick=async()=>{const key=btn.dataset.removePreset,index=Number(btn.dataset.index),value=presets[key][index];presets[key].splice(index,1);await deleteCloudPreset(key,value);savePresets();renderPresets()})
}
function openPresets(){renderPresets();presetModal.classList.add('show');presetModal.setAttribute('aria-hidden','false')}function closePresets(){presetModal.classList.remove('show');presetModal.setAttribute('aria-hidden','true')}$('#presetBtn').onclick=openPresets;$('#closePreset').onclick=closePresets;$('#finishPreset').onclick=closePresets;presetModal.onclick=e=>{if(e.target===presetModal)closePresets()};
function updateProfitPreview(){const amount=Number(form.elements.amount.value)||0,cost=Number(form.elements.cost.value)||0;form.elements.profitPreview.value=`¥${(amount-cost).toLocaleString()}`}
function localToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function openModal(record=null){state.editingKey=record?.key??null;form.reset();fillOptions();statusOptions(record?.statuses||[presets.status[0]||'已付款']);$('#modalTitle').textContent=record?'编辑项目记录':'添加项目记录';$('#deleteRecord').classList.toggle('show',!!record);if(record){['id','category','project','amount','cost','date','owner','client','paymentStatus','note','files'].forEach(k=>form.elements[k].value=record[k]??'')}else{form.elements.category.value=presets.category[0]||'';form.elements.project.value=unique('project')[0]||'__new__';form.elements.owner.value=presets.owner[0]||'';form.elements.paymentStatus.value='未收款';form.elements.date.value=localToday()}updateProfitPreview();form.querySelector('.form-grid').scrollTop=0;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
$('#projectSelect').onchange=e=>{if(e.target.value!=='__new__')return;const value=prompt('请输入新的项目名称')?.trim();if(!value){fillOptions();return}if(!presets.project.includes(value)){presets.project.push(value);localStorage.setItem('projectPresets',JSON.stringify(presets))}fillOptions();e.target.value=value;toast('项目名称已加入预设')};
function bindPresetSelect(selector,key,label){$(selector).onchange=e=>{if(e.target.value!=='__new__')return;const value=prompt(`请输入新的${label}`)?.trim();if(!value){fillOptions();return}if(!presets[key].includes(value)){presets[key].push(value);localStorage.setItem('projectPresets',JSON.stringify(presets))}fillOptions();e.target.value=value;toast(`${label}已加入预设`)}}
bindPresetSelect('#categorySelect','category','项目分类');bindPresetSelect('#ownerSelect','owner','负责人');bindPresetSelect('#paymentSelect','paymentStatus','收款状态');form.elements.amount.oninput=updateProfitPreview;form.elements.cost.oninput=updateProfitPreview;
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');state.editingKey=null}$('#addRecord').onclick=()=>openModal();$('#emptyAdd').onclick=()=>openModal();$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
form.onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),d=Object.fromEntries(fd),statuses=fd.getAll('statuses');if(!statuses.length)return toast('请至少选择一个阶段状态');const max=Math.max(0,...state.records.map(r=>Number(String(r.id).replace(/\D/g,''))||0)),id=String(d.id||`NO.${String(max+1).padStart(3,'0')}`).trim(),amount=Number(d.amount)||0,cost=Number(d.cost)||0,existing=state.records.find(r=>String(r.key)===String(state.editingKey));if(state.records.some(r=>String(r.id).toLowerCase()===id.toLowerCase()&&String(r.key)!==String(state.editingKey)))return toast('项目编号已存在，请更换编号');if(amount<0||cost<0)return toast('金额和成本不能小于 0');snapshot();const values={id,category:d.category,project:d.project,amount:amount||'',cost:cost||'',date:d.date,owner:d.owner,client:d.client,paymentStatus:d.paymentStatus,statuses,files:d.files||'',note:d.note};if(existing){const index=state.records.indexOf(existing);state.records[index]={...existing,...values};if(existing.id!==id)deleteCloudProject(existing.id)}else state.records.push({key:Date.now(),...values});save();closeModal();render()};
async function deleteCloudProject(id){if(!cloud.user||!cloud.client||!id)return;const {error}=await cloud.client.from('projects').delete().eq('id',id);if(error){console.error(error);toast('本地已删除，云端删除失败，请稍后重试')}}
async function deleteCloudPreset(type,value){if(!cloud.user||!cloud.client||!type||!value)return;const {error}=await cloud.client.from('presets').delete().eq('preset_type',type).eq('preset_value',value);if(error){console.error(error);toast('本地已修改，云端预设同步失败')}}
$('#deleteRecord').onclick=()=>{if(!state.editingKey)return;const record=state.records.find(r=>r.key===state.editingKey);if(!record||!confirm(`确定删除项目 ${record.id} 吗？此操作会同步到云端。`))return;snapshot();state.records=state.records.filter(r=>r.key!==state.editingKey);localStorage.setItem('projectRecords',JSON.stringify(state.records));deleteCloudProject(record.id);scheduleCloudSave();toast('项目已删除');closeModal();render()};
const cloudMetaPrefix='__TKEDC_META__:';
function encodeCloudFiles(r){return cloudMetaPrefix+JSON.stringify({paymentStatus:r.paymentStatus||'未收款',files:r.files||''})}
function decodeCloudFiles(value){if(typeof value==='string'&&value.startsWith(cloudMetaPrefix)){try{return JSON.parse(value.slice(cloudMetaPrefix.length))}catch{}}return {paymentStatus:'未收款',files:value||''}}
function projectToCloud(r){return {id:r.id,category:r.category||'',project_name:r.project||'',amount:Number(r.amount)||0,cost:Number(r.cost)||0,start_date:r.date||null,owner:r.owner||'',client:r.client||'',statuses:r.statuses||[],files:encodeCloudFiles(r),note:r.note||'',updated_at:new Date().toISOString()}}
function projectFromCloud(r){const meta=decodeCloudFiles(r.files);return {key:r.id,id:r.id,category:r.category,project:r.project_name,amount:Number(r.amount)||'',cost:Number(r.cost)||'',date:r.start_date||'',owner:r.owner,client:r.client,paymentStatus:meta.paymentStatus||'未收款',statuses:r.statuses||[],files:meta.files||'',note:r.note||''}}
function scheduleCloudSave(){if(!cloud.user||!cloud.client)return;clearTimeout(cloud.timer);cloud.timer=setTimeout(cloudSaveAll,500)}
async function cloudSaveAll(){if(cloud.saving)return scheduleCloudSave();cloud.saving=true;try{const projects=state.records.map(projectToCloud);const presetRows=Object.entries(presets).flatMap(([preset_type,values])=>values.map(preset_value=>({preset_type,preset_value})));let result;if(projects.length){result=await cloud.client.from('projects').upsert(projects);if(result.error)throw result.error}if(presetRows.length){result=await cloud.client.from('presets').upsert(presetRows);if(result.error)throw result.error}setCloudStatus('云端已同步',true)}catch(error){setCloudStatus('同步失败');console.error(error);const message=error?.message||'未知错误';toast(`同步失败：${message.slice(0,42)}`)}finally{cloud.saving=false}}
function setCloudStatus(text,online=false){const synced=online&&text==='云端已同步',time=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});$('#cloudStatus').textContent=synced?`已同步 ${time}`:text;$('#cloudStatus').classList.toggle('online',online);$('#signOutBtn').classList.toggle('show',!!cloud.user);$('#syncNowBtn').classList.toggle('show',!!cloud.user)}
$('#syncNowBtn').onclick=async()=>{if(!cloud.user||cloud.saving)return;setCloudStatus('正在同步…');await cloudSaveAll()};
function showAuth(message=''){const el=$('#authModal');el.classList.add('show');el.setAttribute('aria-hidden','false');$('#authMessage').textContent=message}
function hideAuth(){$('#authModal').classList.remove('show');$('#authModal').setAttribute('aria-hidden','true');$('#authMessage').textContent=''}
async function loadCloudData(){setCloudStatus('正在读取云端…');const [projectsResult,presetsResult]=await Promise.all([cloud.client.from('projects').select('*').order('start_date',{ascending:false}),cloud.client.from('presets').select('*')]);if(projectsResult.error)throw projectsResult.error;if(presetsResult.error)throw presetsResult.error;if(projectsResult.data.length){state.records=projectsResult.data.map(projectFromCloud);localStorage.setItem('projectRecords',JSON.stringify(state.records))}else if(state.records.length){await cloudSaveAll()}if(presetsResult.data.length){Object.keys(presetMeta).forEach(key=>presets[key]=[]);presetsResult.data.forEach(r=>(presets[r.preset_type]??=[]).push(r.preset_value));Object.keys(presetDefaults).forEach(key=>presets[key]=[...new Set([...(presets[key]||[]),...presetDefaults[key]])]);localStorage.setItem('projectPresets',JSON.stringify(presets));syncStatuses();updateStatusFilter()}setCloudStatus('云端已同步',true);render()}
async function initCloud(){const cfg=window.CLOUD_CONFIG;if(!cfg?.supabaseUrl||!cfg?.supabasePublishableKey||!window.supabase)return setCloudStatus('仅本地模式');cloud.client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const {data:{session}}=await cloud.client.auth.getSession();if(!session){setCloudStatus('请登录');return showAuth()}cloud.user=session.user;hideAuth();try{await loadCloudData()}catch(error){console.error(error);setCloudStatus('数据库未就绪');showAuth('请先在 Supabase SQL Editor 执行 supabase-schema.sql')}}
$('#authForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));$('#authMessage').textContent='正在登录…';const {data,error}=await cloud.client.auth.signInWithPassword({email:d.email,password:d.password});if(error)return $('#authMessage').textContent=error.message;cloud.user=data.user;hideAuth();try{await loadCloudData()}catch(err){showAuth('数据库未就绪，请先执行 SQL 建表文件')}};
$('#registerBtn').onclick=async()=>{const form=$('#authForm'),email=form.elements.email.value,password=form.elements.password.value;if(!email||password.length<6)return $('#authMessage').textContent='请输入邮箱和至少 6 位密码';$('#authMessage').textContent='正在创建账号…';const {data,error}=await cloud.client.auth.signUp({email,password});if(error)return $('#authMessage').textContent=error.message;if(data.session){cloud.user=data.user;hideAuth();await loadCloudData()}else $('#authMessage').textContent='注册成功，请查收验证邮件后再登录'};
$('#signOutBtn').onclick=async()=>{await cloud.client.auth.signOut();cloud.user=null;setCloudStatus('已退出');showAuth('已退出登录')};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal.classList.contains('show'))closeModal();if(presetModal.classList.contains('show'))closePresets()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#tableSearch').focus();$('#tableSearch').select()}});window.addEventListener('resize',updateStickyOffsets);$('#todayLabel').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());initColumnMovement();initColumnResize();updateStatusFilter();updateFilterText();$('#rowHeight').value=String(state.rowHeight);$('#columnWidth').value=state.columnWidth;applyColumnWidth();restoreColumnWidths();$('#hideDone').checked=state.hideDone;$('#groupBtn').textContent=state.groupBy==='project'?'▦ 按项目分组':'▦ 按分类分组';refreshSortUi();render();initCloud();
