(function(){
  const selectedKeys=new Set();
  const hiddenColumns=new Set(JSON.parse(localStorage.getItem('projectHiddenColumns')||'[]').map(Number));
  const columnLabels={4:'开始时间',5:'金额',6:'项目成本',7:'利润',8:'负责人',9:'客户信息',10:'收款状态',11:'阶段状态',12:'备注',13:'资料'};
  state.quickFilter='all';
  state.financeFrom=localStorage.getItem('financeFrom')||'';
  state.financeTo=localStorage.getItem('financeTo')||'';
  state.financeCategory=localStorage.getItem('financeCategory')||'all';
  state.financePayment=localStorage.getItem('financePayment')||'all';
  state.boardFrom=localStorage.getItem('boardFrom')||'';
  state.boardTo=localStorage.getItem('boardTo')||'';
  state.boardCategory=localStorage.getItem('boardCategory')||'all';
  state.customerSort=localStorage.getItem('customerSort')||'recent';

  function isIncomplete(r){return !String(r.category||'').trim()||!String(r.project||'').trim()||!String(r.date||'').trim()||!String(r.client||'').trim()||!String(r.owner||'').trim()||!Number(r.amount)||!(r.statuses||[]).length}
  function dateRange(kind){const now=new Date(),today=localToday();if(kind==='today')return [today,today];if(kind==='month')return [today.slice(0,7)+'-01',today.slice(0,7)+'-31'];const day=(now.getDay()+6)%7,start=new Date(now);start.setDate(now.getDate()-day);const end=new Date(start);end.setDate(start.getDate()+6);const fmt=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return [fmt(start),fmt(end)]}
  function matchesQuickFilter(r){const kind=state.quickFilter;if(kind==='all')return true;if(['today','week','month'].includes(kind)){const [from,to]=dateRange(kind);return String(r.date||'')>=from&&String(r.date||'')<=to}if(kind==='unpaid')return ['未收款','部分收款'].includes(r.paymentStatus);if(kind==='review')return (r.statuses||[]).includes('审核中');if(kind==='pending')return !(r.statuses||[]).includes('交付完成');if(kind==='incomplete')return isIncomplete(r);return true}

  const originalFiltered=filtered;
  filtered=function(){return originalFiltered().filter(matchesQuickFilter)};

  function normalizedCustomer(value){return String(value||'').trim().toLowerCase().replace(/[\s+＋()（）\-—_]/g,'')}
  customerProfiles=function(){const groups=new Map();let missing=0;state.records.forEach(r=>{const raw=String(r.client||'').trim();if(!raw){missing++;return}const key=normalizedCustomer(raw),item=groups.get(key)||{names:new Map(),records:[],projects:new Set(),latestDate:''};item.names.set(raw,(item.names.get(raw)||0)+1);item.records.push(r);item.projects.add(r.project||defaultProjectName);if((r.date||'')>=item.latestDate)item.latestDate=r.date||'';groups.set(key,item)});const items=[...groups.values()].map(item=>({...item,contact:[...item.names].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'zh-CN'))[0][0]})).sort((a,b)=>String(b.latestDate).localeCompare(String(a.latestDate))||a.contact.localeCompare(b.contact,'zh-CN',{numeric:true}));return {items,missing}}
  function duplicateCustomerGroups(){const groups=new Map();state.records.forEach(r=>{const raw=String(r.client||'').trim();if(!raw)return;const key=normalizedCustomer(raw),set=groups.get(key)||new Set();set.add(raw);groups.set(key,set)});return [...groups.entries()].filter(([,names])=>names.size>1)}

  function saveAutomaticBackup(label='自动备份'){const records=JSON.parse(JSON.stringify(state.records)),list=JSON.parse(localStorage.getItem('projectBackups')||'[]');list.unshift({id:Date.now(),time:new Date().toISOString(),label,records});localStorage.setItem('projectBackups',JSON.stringify(list.slice(0,10)))}
  const originalSnapshot=snapshot;
  snapshot=function(){saveAutomaticBackup();originalSnapshot()};
  function backupList(){const local=JSON.parse(localStorage.getItem('projectBackups')||'[]');const cloudRows=(presets.__backup__||[]).map(v=>{try{return {...JSON.parse(v),cloud:true}}catch{return null}}).filter(Boolean);const seen=new Set();return [...local,...cloudRows].filter(x=>x?.records&&x.time&&!seen.has(x.time)&&(seen.add(x.time),true)).sort((a,b)=>String(b.time).localeCompare(String(a.time))).slice(0,12)}
  async function createManualBackup(){const item={id:Date.now(),time:new Date().toISOString(),label:'手动备份',records:JSON.parse(JSON.stringify(state.records))},list=JSON.parse(localStorage.getItem('projectBackups')||'[]');list.unshift(item);localStorage.setItem('projectBackups',JSON.stringify(list.slice(0,10)));if(cloud.user&&cloud.client){const value=JSON.stringify(item);presets.__backup__=[value,...(presets.__backup__||[])].slice(0,5);const {error}=await cloud.client.from('presets').upsert({preset_type:'__backup__',preset_value:value});if(error)console.error(error)}renderBackupList();toast(cloud.user?'备份已保存到本地和云端':'备份已保存到本地')}
  function restoreBackup(item){if(!item||!confirm(`恢复 ${new Date(item.time).toLocaleString('zh-CN')} 的备份吗？当前数据会先自动备份。`))return;snapshot();state.records=JSON.parse(JSON.stringify(item.records));selectedKeys.clear();save();render();closeBackupPanel();toast('备份已恢复')}
  function renderBackupList(){const box=document.querySelector('#backupList');if(!box)return;const list=backupList();box.innerHTML=list.length?list.map((item,i)=>`<div class="backup-item"><div><strong>${esc(item.label||'数据备份')}</strong><small>${new Date(item.time).toLocaleString('zh-CN')} · ${item.records.length} 条${item.cloud?' · 云端':''}</small></div><button type="button" data-restore="${i}">恢复</button></div>`).join(''):'<div class="backup-empty">暂无备份</div>';box.querySelectorAll('[data-restore]').forEach(btn=>btn.onclick=()=>restoreBackup(list[Number(btn.dataset.restore)]))}
  function openBackupPanel(){document.querySelector('#backupModal').classList.add('show');renderBackupList()}
  function closeBackupPanel(){document.querySelector('#backupModal').classList.remove('show')}
  function exportJson(){downloadFile(`项目完整备份-${localToday()}.json`,JSON.stringify({version:1,time:new Date().toISOString(),records:state.records,presets},null,2),'application/json;charset=utf-8');toast('完整备份已导出')}
  function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),records=Array.isArray(data)?data:data.records;if(!Array.isArray(records))throw new Error();if(!confirm(`导入 ${records.length} 条项目记录吗？当前数据会先自动备份。`))return;snapshot();state.records=records;save();render();closeBackupPanel();toast('备份已导入')}catch{toast('备份文件格式不正确')}};reader.readAsText(file)}

  function applyColumnVisibility(){hiddenColumns.forEach(i=>{document.querySelectorAll(`[data-col="${i}"]`).forEach(el=>el.classList.add('column-hidden'))});Object.keys(columnLabels).map(Number).filter(i=>!hiddenColumns.has(i)).forEach(i=>document.querySelectorAll(`[data-col="${i}"]`).forEach(el=>el.classList.remove('column-hidden')))}
  function updateColumnPanel(){document.querySelectorAll('#columnPanel input').forEach(input=>input.checked=!hiddenColumns.has(Number(input.value)))}
  function toggleColumn(i,show){show?hiddenColumns.delete(i):hiddenColumns.add(i);localStorage.setItem('projectHiddenColumns',JSON.stringify([...hiddenColumns]));applyColumnVisibility()}

  function linkifyFiles(){document.querySelectorAll('.data-row td[data-col="13"]').forEach(cell=>{const text=cell.textContent.trim();if(!/^https?:\/\//i.test(text))return;cell.innerHTML='';const link=document.createElement('a');link.className='file-link';link.href=text;link.target='_blank';link.rel='noopener';link.textContent='打开资料 ↗';link.title=text;link.onclick=e=>e.stopPropagation();cell.appendChild(link)})}
  function visibleRecords(){return filtered()}
  function updateSelectionUi(){const bar=document.querySelector('#batchBar'),count=document.querySelector('#selectedCount');if(!bar)return;bar.classList.toggle('show',selectedKeys.size>0);count.textContent=`已选择 ${selectedKeys.size} 条`;const rows=visibleRecords(),all=rows.length&&rows.every(r=>selectedKeys.has(recordKey(r))),selectAll=document.querySelector('#selectAllRows');if(selectAll){selectAll.checked=!!all;selectAll.indeterminate=!all&&rows.some(r=>selectedKeys.has(recordKey(r)))}}
  function enhanceRowSelection(){const head=document.querySelector('thead .rownum');if(head&&!head.querySelector('#selectAllRows')){head.innerHTML='<label class="select-all"><input type="checkbox" id="selectAllRows"><span>序号</span></label>';head.querySelector('input').onclick=e=>{e.stopPropagation();visibleRecords().forEach(r=>e.target.checked?selectedKeys.add(recordKey(r)):selectedKeys.delete(recordKey(r)));render()}}document.querySelectorAll('.data-row').forEach(row=>{const cell=row.querySelector('.row-index');if(!cell||cell.querySelector('.row-select'))return;const input=document.createElement('input');input.type='checkbox';input.className='row-select';input.checked=selectedKeys.has(row.dataset.key);input.onclick=e=>{e.stopPropagation();e.target.checked?selectedKeys.add(row.dataset.key):selectedKeys.delete(row.dataset.key);updateSelectionUi()};cell.prepend(input)})}
  function batchRecords(){return state.records.filter(r=>selectedKeys.has(recordKey(r)))}
  function batchChange(field,label){const rows=batchRecords();if(!rows.length)return;const options=field==='statuses'?allStatuses:unique(field),value=prompt(`批量修改${label}\n可选：${options.join('、')}`,options[0]||'')?.trim();if(!value)return;snapshot();rows.forEach(r=>{if(field==='statuses')r.statuses=[value];else r[field]=value});save();selectedKeys.clear();render();toast(`${rows.length} 条记录已更新`)}
  function batchDelete(){const rows=batchRecords();if(!rows.length||!confirm(`确定删除选中的 ${rows.length} 条记录吗？`))return;snapshot();state.records=state.records.filter(r=>!selectedKeys.has(recordKey(r)));rows.forEach(r=>deleteCloudProject(r.id));selectedKeys.clear();save();render();toast('选中记录已删除')}
  function undoLast(){if(!state.history.length)return toast('暂无可撤销操作');const current=state.records.slice(),previous=JSON.parse(state.history.pop()),previousIds=new Set(previous.map(r=>String(r.id)));current.filter(r=>!previousIds.has(String(r.id))).forEach(r=>deleteCloudProject(r.id));state.records=previous;localStorage.setItem('projectRecords',JSON.stringify(state.records));scheduleCloudSave();selectedKeys.clear();render();toast('已撤销上一步操作')}

  function updateHealth(){const count=state.records.filter(isIncomplete).length,button=document.querySelector('[data-quick="incomplete"]'),badge=document.querySelector('#dataHealth');if(button)button.textContent=`资料待补 ${count}`;if(badge){badge.textContent=count?`${count} 条资料待补`:'数据完整';badge.classList.toggle('ok',!count)}const undo=document.querySelector('#undoBtn');if(undo)undo.disabled=!state.history.length}
  function mergeDuplicateCustomers(){const groups=duplicateCustomerGroups();if(!groups.length)return toast('没有发现重复客户');if(!confirm(`发现 ${groups.length} 组相似客户，是否统一为使用次数最多的名称？`))return;snapshot();groups.forEach(([key])=>{const rows=state.records.filter(r=>normalizedCustomer(r.client)===key),counts=rows.reduce((o,r)=>(o[r.client]=(o[r.client]||0)+1,o),{}),canonical=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];rows.forEach(r=>r.client=canonical)});save();render();toast('重复客户已合并')}
  function enhanceCustomerView(){const toolbar=document.querySelector('.customer-toolbar');if(!toolbar||toolbar.querySelector('#mergeCustomersBtn'))return;const duplicates=duplicateCustomerGroups().length,button=document.createElement('button');button.id='mergeCustomersBtn';button.className='merge-customers';button.type='button';button.textContent=duplicates?`合并重复客户 ${duplicates}`:'无重复客户';button.disabled=!duplicates;button.onclick=mergeDuplicateCustomers;toolbar.insertBefore(button,toolbar.querySelector('#customerResultCount'))}

  const originalRenderFinance=renderFinance;
  renderFinance=function(){const all=state.records;state.records=all.filter(r=>(!state.financeFrom||String(r.date||'')>=state.financeFrom)&&(!state.financeTo||String(r.date||'')<=state.financeTo));try{originalRenderFinance()}finally{state.records=all}const dashboard=document.querySelector('.finance-dashboard');if(!dashboard)return;dashboard.insertAdjacentHTML('afterbegin',`<div class="finance-range"><strong>统计日期</strong><label>从 <input type="date" id="financeFrom" value="${esc(state.financeFrom)}"></label><label>到 <input type="date" id="financeTo" value="${esc(state.financeTo)}"></label><button type="button" id="financeRangeClear">全部日期</button></div>`);const unpaid=all.filter(r=>['未收款','部分收款'].includes(r.paymentStatus)&&(!state.financeFrom||String(r.date||'')>=state.financeFrom)&&(!state.financeTo||String(r.date||'')<=state.financeTo)).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')));dashboard.insertAdjacentHTML('beforeend',`<section class="finance-panel unpaid-panel"><div class="panel-title"><h3>未收款提醒</h3><span>${unpaid.length} 个项目</span></div><div class="report-scroll"><table class="report-table"><thead><tr><th>开始时间</th><th>项目</th><th>客户</th><th>收款状态</th><th>金额</th></tr></thead><tbody>${unpaid.length?unpaid.map(r=>`<tr><td>${esc(r.date||'未填写')}</td><td>${esc(r.project||'')}</td><td>${esc(r.client||'')}</td><td><span class="payment-badge pay-${esc(r.paymentStatus)}">${esc(r.paymentStatus)}</span></td><td class="report-money">¥${Number(r.amount||0).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="5">当前没有待收款项目</td></tr>'}</tbody></table></div></section>`);const refresh=()=>{state.financeFrom=document.querySelector('#financeFrom').value;state.financeTo=document.querySelector('#financeTo').value;localStorage.setItem('financeFrom',state.financeFrom);localStorage.setItem('financeTo',state.financeTo);renderFinance()};document.querySelector('#financeFrom').onchange=refresh;document.querySelector('#financeTo').onchange=refresh;document.querySelector('#financeRangeClear').onclick=()=>{state.financeFrom='';state.financeTo='';localStorage.removeItem('financeFrom');localStorage.removeItem('financeTo');renderFinance()}}

  const originalFilteredCustomers=filteredCustomers;
  filteredCustomers=function(items){const rows=originalFilteredCustomers(items);if(state.customerSort==='count')return rows.sort((a,b)=>b.records.length-a.records.length||String(b.latestDate).localeCompare(String(a.latestDate)));if(state.customerSort==='name')return rows.sort((a,b)=>a.contact.localeCompare(b.contact,'zh-CN',{numeric:true}));return rows.sort((a,b)=>String(b.latestDate).localeCompare(String(a.latestDate)))};
  const originalEnhanceCustomerView=enhanceCustomerView;
  enhanceCustomerView=function(){originalEnhanceCustomerView();const toolbar=document.querySelector('.customer-toolbar');if(!toolbar||toolbar.querySelector('#customerSort'))return;const select=document.createElement('select');select.id='customerSort';select.className='customer-sort';select.innerHTML=`<option value="recent">最近有项目</option><option value="count">项目记录最多</option><option value="name">客户名称</option>`;select.value=state.customerSort;select.onchange=()=>{state.customerSort=select.value;localStorage.setItem('customerSort',state.customerSort);updateCustomerList(customerProfiles().items)};toolbar.insertBefore(select,toolbar.querySelector('#mergeCustomersBtn'))};

  const originalRenderBoard=renderBoard;
  renderBoard=function(){const all=state.records,categories=[...new Set(all.map(r=>r.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN')),rows=all.filter(r=>(state.boardCategory==='all'||r.category===state.boardCategory)&&(!state.boardFrom||String(r.date||'')>=state.boardFrom)&&(!state.boardTo||String(r.date||'')<=state.boardTo));state.records=rows;try{originalRenderBoard()}finally{state.records=all}const dashboard=document.querySelector('.chart-dashboard');if(!dashboard)return;dashboard.insertAdjacentHTML('afterbegin',`<div class="report-filter-bar"><strong>图表范围</strong><label>从 <input type="date" id="boardFrom" value="${esc(state.boardFrom)}"></label><label>到 <input type="date" id="boardTo" value="${esc(state.boardTo)}"></label><label>分类 <select id="boardCategory"><option value="all">全部分类</option>${categories.map(v=>`<option value="${esc(v)}" ${state.boardCategory===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label><span>当前 ${rows.length} / ${all.length} 条</span><button type="button" id="boardFilterClear">重置</button></div>`);const amountData=aggregate(rows,r=>r.project,r=>Number(r.amount)||0).slice(0,8);dashboard.querySelector('.chart-grid')?.insertAdjacentHTML('beforeend',`<section class="chart-panel"><div class="panel-title"><h3>项目金额排行</h3><span>前 8 个项目</span></div>${projectBars(amountData)}</section>`);const refresh=()=>{state.boardFrom=document.querySelector('#boardFrom').value;state.boardTo=document.querySelector('#boardTo').value;state.boardCategory=document.querySelector('#boardCategory').value;localStorage.setItem('boardFrom',state.boardFrom);localStorage.setItem('boardTo',state.boardTo);localStorage.setItem('boardCategory',state.boardCategory);renderBoard()};document.querySelector('#boardFrom').onchange=refresh;document.querySelector('#boardTo').onchange=refresh;document.querySelector('#boardCategory').onchange=refresh;document.querySelector('#boardFilterClear').onclick=()=>{state.boardFrom='';state.boardTo='';state.boardCategory='all';localStorage.removeItem('boardFrom');localStorage.removeItem('boardTo');localStorage.removeItem('boardCategory');renderBoard()}};

  const dateFilteredRenderFinance=renderFinance;
  renderFinance=function(){const all=state.records,categories=[...new Set(all.map(r=>r.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN')),payments=[...new Set([...(presets.paymentStatus||[]),...all.map(r=>r.paymentStatus).filter(Boolean)])],scoped=all.filter(r=>(state.financeCategory==='all'||r.category===state.financeCategory)&&(state.financePayment==='all'||r.paymentStatus===state.financePayment));state.records=scoped;try{dateFilteredRenderFinance()}finally{state.records=all}const range=document.querySelector('.finance-range');if(!range)return;range.insertAdjacentHTML('beforeend',`<label>分类 <select id="financeCategory"><option value="all">全部分类</option>${categories.map(v=>`<option value="${esc(v)}" ${state.financeCategory===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>收款 <select id="financePayment"><option value="all">全部状态</option>${payments.map(v=>`<option value="${esc(v)}" ${state.financePayment===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`);const rows=scoped.filter(r=>(!state.financeFrom||String(r.date||'')>=state.financeFrom)&&(!state.financeTo||String(r.date||'')<=state.financeTo)),received=rows.filter(r=>r.paymentStatus==='已收款').reduce((n,r)=>n+(Number(r.amount)||0),0),pending=rows.filter(r=>['未收款','部分收款'].includes(r.paymentStatus)).reduce((n,r)=>n+(Number(r.amount)||0),0),rate=received+pending?Math.round(received/(received+pending)*100):0;range.insertAdjacentHTML('afterend',`<div class="collection-overview"><div><span>已收项目金额</span><strong>¥${received.toLocaleString()}</strong></div><div><span>待收项目金额</span><strong>¥${pending.toLocaleString()}</strong></div><div><span>项目回款率</span><strong>${rate}%</strong></div><small>部分收款因未记录具体已收金额，暂计入待收项目</small></div>`);const refresh=()=>{state.financeCategory=document.querySelector('#financeCategory').value;state.financePayment=document.querySelector('#financePayment').value;localStorage.setItem('financeCategory',state.financeCategory);localStorage.setItem('financePayment',state.financePayment);renderFinance()};document.querySelector('#financeCategory').onchange=refresh;document.querySelector('#financePayment').onchange=refresh};

  function injectControls(){
    document.querySelector('.tool-main').insertAdjacentHTML('beforeend','<button class="pill" id="undoBtn" type="button">撤销</button><button class="pill" id="backupBtn" type="button">备份恢复</button>');
    document.querySelector('.tool-options').insertAdjacentHTML('afterbegin','<button class="pill" id="columnBtn" type="button">显示列</button>');
    document.querySelector('#filterPanel').insertAdjacentHTML('afterend','<section class="quick-filter-bar" id="quickFilterBar"><span>快捷查看</span><button data-quick="all" class="active">全部</button><button data-quick="today">今天</button><button data-quick="week">本周</button><button data-quick="month">本月</button><button data-quick="unpaid">未收款</button><button data-quick="review">审核中</button><button data-quick="pending">待交付</button><button data-quick="incomplete">资料待补 0</button><i id="dataHealth"></i></section><section class="batch-bar" id="batchBar"><strong id="selectedCount">已选择 0 条</strong><button data-batch="category">修改分类</button><button data-batch="owner">修改负责人</button><button data-batch="statuses">修改阶段</button><button class="danger" id="batchDelete">批量删除</button><button id="clearSelection">取消选择</button></section>');
    document.body.insertAdjacentHTML('beforeend',`<div class="column-panel" id="columnPanel"><div><strong>显示栏目</strong><button type="button" id="closeColumnPanel">×</button></div>${Object.entries(columnLabels).map(([i,label])=>`<label><input type="checkbox" value="${i}" ${hiddenColumns.has(Number(i))?'':'checked'}>${label}</label>`).join('')}</div><div class="modal backup-modal" id="backupModal"><div class="modal-card backup-card"><div class="modal-head"><div><h2>备份与恢复</h2><p>自动保留最近 10 个版本，登录后手动备份也会保存到云端</p></div><button type="button" id="closeBackup">×</button></div><div class="backup-actions"><button type="button" id="createBackup">创建备份</button><button type="button" id="exportJson">导出完整备份</button><label>导入备份<input type="file" id="importJson" accept="application/json,.json"></label></div><div class="backup-list" id="backupList"></div></div></div>`);
    document.querySelectorAll('[data-quick]').forEach(btn=>btn.onclick=()=>{state.quickFilter=btn.dataset.quick;document.querySelectorAll('[data-quick]').forEach(x=>x.classList.toggle('active',x===btn));render()});
    document.querySelector('#undoBtn').onclick=undoLast;document.querySelector('#backupBtn').onclick=openBackupPanel;document.querySelector('#closeBackup').onclick=closeBackupPanel;document.querySelector('#backupModal').onclick=e=>{if(e.target.id==='backupModal')closeBackupPanel()};document.querySelector('#createBackup').onclick=createManualBackup;document.querySelector('#exportJson').onclick=exportJson;document.querySelector('#importJson').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};
    document.querySelector('#columnBtn').onclick=e=>{const panel=document.querySelector('#columnPanel'),rect=e.target.getBoundingClientRect();panel.style.top=`${rect.bottom+7}px`;panel.style.right='18px';panel.classList.toggle('show');updateColumnPanel()};document.querySelector('#closeColumnPanel').onclick=()=>document.querySelector('#columnPanel').classList.remove('show');document.querySelectorAll('#columnPanel input').forEach(input=>input.onchange=()=>toggleColumn(Number(input.value),input.checked));
    document.querySelectorAll('[data-batch]').forEach(btn=>btn.onclick=()=>batchChange(btn.dataset.batch,{category:'项目分类',owner:'负责人',statuses:'阶段状态'}[btn.dataset.batch]));document.querySelector('#batchDelete').onclick=batchDelete;document.querySelector('#clearSelection').onclick=()=>{selectedKeys.clear();render()};
    document.querySelector('#addRecord').title='快捷键 N';document.querySelector('#undoBtn').title='快捷键 Ctrl+Z';document.querySelector('#backupBtn').title='创建、导入或恢复备份';document.querySelector('#columnBtn').title='选择需要显示的表格栏目';document.querySelector('#syncNowBtn').title='快捷键 Ctrl+S';
  }

  function enhanceDataQuality(){document.querySelectorAll('.data-row').forEach(row=>{const record=state.records.find(r=>recordKey(r)===row.dataset.key);if(!record)return;const fields=[[4,!record.date,'缺少开始时间'],[5,!Number(record.amount),'缺少项目金额'],[9,!String(record.client||'').trim(),'缺少客户信息'],[11,!(record.statuses||[]).length,'缺少阶段状态']];row.classList.toggle('needs-data',isIncomplete(record));fields.forEach(([index,missing,label])=>{const cell=row.querySelector(`[data-col="${index}"]`);if(cell){cell.classList.toggle('missing-cell',missing);if(missing)cell.title=label}})})}
  function updateFilterSummary(){let el=document.querySelector('#activeFilterSummary');if(!el){el=document.createElement('span');el.id='activeFilterSummary';document.querySelector('.view-heading>div').appendChild(el)}const quick={today:'今天',week:'本周',month:'本月',unpaid:'未收款',review:'审核中',pending:'待交付',incomplete:'资料待补'}[state.quickFilter],parts=[quick,state.status!=='all'?state.status:'',state.payment!=='all'?state.payment:'',state.hideDone?'隐藏已交付':'',state.search?`搜索：${state.search}`:''].filter(Boolean);el.textContent=parts.length?`当前条件：${parts.join(' · ')}`:'';el.classList.toggle('show',parts.length>0)}
  function enhancedAfterRender(){enhanceRowSelection();applyColumnVisibility();linkifyFiles();enhanceDataQuality();updateSelectionUi();updateHealth();updateFilterSummary();enhanceCustomerView();document.querySelector('#quickFilterBar')?.classList.toggle('view-hidden',state.view!=='table');document.querySelector('#batchBar')?.classList.toggle('view-hidden',state.view!=='table');document.querySelector('#activeFilterSummary')?.classList.toggle('view-hidden',state.view!=='table')}
  document.addEventListener('click',e=>{const panel=document.querySelector('#columnPanel');if(panel?.classList.contains('show')&&!panel.contains(e.target)&&e.target.id!=='columnBtn')panel.classList.remove('show')});
  document.addEventListener('keydown',e=>{const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'');if(e.key==='Escape'){document.querySelector('#columnPanel')?.classList.remove('show');closeBackupPanel()}if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoLast()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();cloud.user?cloudSaveAll():toast('当前数据已自动保存在本地')}else if(e.key.toLowerCase()==='n'){e.preventDefault();if(state.view!=='table')setView('table');openModal()}else if(e.key==='/'){e.preventDefault();document.querySelector('#tableSearch')?.focus()}});
  const originalRender=render;
  render=function(){originalRender();enhancedAfterRender()};
  const originalSetView=setView;
  setView=function(view){originalSetView(view);enhancedAfterRender()};
  injectControls();enhancedAfterRender();
})();
